/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2026-06-01 13:02:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import model.SanPham;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.SanPham");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<title>Quản lý sản phẩm</title>\n");
      out.write("\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\n");
      out.write("      rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"bg-light\">\n");
      out.write("\n");
      out.write("<div class=\"container mt-4\">\n");
      out.write("\n");
      out.write("<h1 class=\"text-center text-primary mb-4\">\n");
      out.write("🛒 Quản Lý Sản Phẩm\n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("<form action=\"product\"\n");
      out.write("      class=\"row mb-4\">\n");
      out.write("\n");
      out.write("<div class=\"mb-3\">\n");
      out.write("    <a href=\"addProduct.jsp\" class=\"btn btn-success\">\n");
      out.write("        ➕ Thêm sản phẩm\n");
      out.write("    </a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"col-md-10\">\n");
      out.write("\n");
      out.write("<input\n");
      out.write("class=\"form-control\"\n");
      out.write("name=\"keyword\"\n");
      out.write("value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("placeholder=\"Nhập tên sản phẩm...\">\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"col-md-2\">\n");
      out.write("\n");
      out.write("<button class=\"btn btn-primary w-100\">\n");
      out.write("\n");
      out.write("Tìm kiếm\n");
      out.write("\n");
      out.write("</button>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("\n");
      out.write("    ");

List<SanPham> list =
(List<SanPham>)request.getAttribute("list");

if(list!=null){

for(SanPham sp:list){

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"col-md-3 mb-4\">\n");
      out.write("\n");
      out.write("<div class=\"card shadow\">\n");
      out.write("\n");
      out.write("<img\n");
      out.write("src=\"");
      out.print(sp.getHinhAnh());
      out.write("\"\n");
      out.write("style=\"height:220px;object-fit:cover\"\n");
      out.write("class=\"card-img-top\">\n");
      out.write("\n");
      out.write("<div class=\"card-body\">\n");
      out.write("\n");
      out.write("<h5>");
      out.print(sp.getTenSP());
      out.write("</h5>\n");
      out.write("\n");
      out.write("<p>\n");
      out.print(sp.getMoTa());
      out.write("\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("<h4 class=\"text-danger\">\n");
      out.write("\n");
      out.print(String.format("%,.0f",sp.getGia()));
      out.write(" VNĐ\n");
      out.write("\n");
      out.write("</h4>\n");
      out.write("\n");
      out.write("<a href=\"editProduct?id=");
      out.print(sp.getMaSP());
      out.write("\"\n");
      out.write("class=\"btn btn-warning\">\n");
      out.write("\n");
      out.write("Sửa\n");
      out.write("\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("<a href=\"deleteProduct?id=");
      out.print(sp.getMaSP());
      out.write("\"\n");
      out.write("class=\"btn btn-danger\">\n");
      out.write("\n");
      out.write("Xóa\n");
      out.write("\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");

}
}

      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
